version: '3.3'
services:
  asterisk:
    container_name: asterisk
    volumes:
        - soundsVolume:/var/lib/asterisk/sounds/
        - configVolume:/etc/asterisk/
    network_mode: host
    image: asterisk
    command: bash -c
             'chown -R :1024 /etc/asterisk &&
             chown -R :1024 /var/lib/asterisk/sounds/voice &&
             chmod -R 777 /var/lib/asterisk/sounds/voice &&
             /bin/sh /start.sh'
  voiceflow:
      container_name: voiceflow
      volumes:
          - soundsVolume:/var/lib/asterisk/sounds/
          - configVolume:/etc/asterisk/
          - /home/max/Documents:/home/Documents
          - '/tmp/.X11-unix:/tmp/.X11-unix'
      network_mode: host
      environment:
          - DISPLAY=$DISPLAY
      user: qtuser
      image: voiceflow
volumes:
  soundsVolume:
  configVolume:
